import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/store/store";
import { ThemeProvider } from "next-themes";
import Navbar from "@/components/ui/Navbar";
import { Toaster } from "@/components/ui/toaster";
import { cookies } from "next/headers";
import { jwtVerify } from "jose";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const JWT_SECRET = new TextEncoder().encode(
  process.env.JWT_SECRET || "your-super-secret-key-change-in-production",
);

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const sessionToken = cookieStore.get("session")?.value;

  const user={username:'' , id:'' , email:'',phone:'' ,role:''};
  if(sessionToken){
    const {payload} = await jwtVerify(sessionToken, JWT_SECRET) ;
    user.username=payload.username as string;
    user.email=payload.email as string;
    user.phone=payload.phone as string;
    user.role=payload.role as string;
    user.id=payload.userId as string;

    
  }


  return (
    <StoreProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased  main-bg`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            disableTransitionOnChange
          >
            {/* <Sidebar /> */}
            <Navbar user={user} />
            <main className="h-[calc(100vh-66px)] overflow-hidden">
              {children}
            </main>
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </StoreProvider>
  );
}
